=== trantrithuc/trantrithuc.github.io/JavaScript/Ajaxform/xml/data.dtd
<!ELEMENT users(user+)>
<!ELEMENT user(username,password,email,birthday)>
<!ELEMENT username(#PCDATA)>
<!ELEMENT password(#PCDATA)>
<!ELEMENT email(#PCDATA)>
<!ELEMENT birthday(#PCDATA)>

=== trantrithuc/trantrithuc.github.io/JavaScript/Ajaxform/xml/data.xml
<?xml version = "1.0" ?>
<!DOCTYPE users SYSTEM "DATA.dtd">
<users>
	<user>
		<username>THUC</username>
		<password>123</password>
		<email>TRANTRITHUC@GMAIL.COM</email>
		<birthday>23/01/1994</birthday>
	</user>
 	<user>
   		<username>ADMIN</username>
  		<password>123456</password>
   		<email>admin@gmail.com</email>
   		<birthday>20/01/1990</birthday>
  	</user>
	<user>
   		<username>abc</username>
  		<password>123456</password>
   		<email>admin@gmail.com</email>
   		<birthday>20/01/1990</birthday>
  	</user>
</users>
